#!/bin/bash -l
#PBS -l mem=4gb
#PBS -l nodes=1:ppn=1
#PBS -l walltime=100:00:00

cd "/projects3/mlg/IB2/creggian/epigenome/release9/sample-experiment"
find `pwd` -name *.gz | xargs -I {} -- sh -c "echo -n -e '{}\t'; zcat {} | head -n 1 | awk '{print NF}'" | grep 5$ | cut -f1 | xargs -I {} -- sh -c "zcat {} | awk '{print \$1 \"\t\" \$2 \"\t\" \$3 \"\t\" \$4 \"\t\" 0 \"\t\" \$5}' | gzip > {}.fixed.gz"
